[tool.poetry]
name = "recipes"
version = "0.1.0"
description = "My own favorite recipes"
authors = ["Jessica Benson <pokeyjess72@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1"

Django-cleanup = 5.0.0

Pillow = 7.2.0

poetry >= 0.12

whitenoise = 5.2.0
gunicorn==20.0.4
