# Generated by Django 3.1 on 2020-10-04 06:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_photo3.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
